// data/services/pdf_service.dart
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../core/constants/enums.dart';
import '../models/models.dart';

class PdfService {
  static pw.Font? _regularFont;

  static Future<void> _ensureFonts() async {
    _regularFont ??= pw.Font.ttf(
      await rootBundle.load('assets/fonts/Kanit-Regular.ttf'),
    );
  }

  static pw.Font get _regular => _regularFont!;

  static final _currencyFormat = NumberFormat.currency(
    symbol: '₦',
    decimalDigits: 0,
  );
  static final _dateFormat = DateFormat('dd MMM yyyy');
  static const String _associationName = 'Age Grade Association';
  static const String _footerText = 'Generated by Age Grade Finance App';

  static pw.TextStyle _regularStyle({
    double? fontSize,
    pw.FontWeight? fontWeight,
    PdfColor? color,
  }) {
    return pw.TextStyle(
      font: _regular,
      fontSize: fontSize,
      fontWeight: fontWeight,
      color: color,
    );
  }

  static String _fmt(double amount) => _currencyFormat.format(amount);
  static String _fmtDate(DateTime date) => _dateFormat.format(date);

  static pw.Widget _buildHeader(String title, {List<String>? subtitles}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          _associationName,
          style: _regularStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          title,
          style: _regularStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
        ),
        if (subtitles != null)
          ...subtitles.map(
            (s) => pw.Padding(
              padding: const pw.EdgeInsets.only(top: 2),
              child: pw.Text(s, style: _regularStyle(fontSize: 11)),
            ),
          ),
        pw.Divider(),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 8),
      child: pw.Text(
        '$_footerText  |  Page ${context.pageNumber} of ${context.pagesCount}',
        style: _regularStyle(fontSize: 9, color: PdfColors.grey),
      ),
    );
  }

  static pw.Table _buildTable({
    required List<String> headers,
    required List<List<String?>> rows,
  }) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        for (var i = 0; i < headers.length; i++)
          i: const pw.IntrinsicColumnWidth(),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey300),
          children: headers
              .map(
                (h) => pw.Padding(
                  padding: const pw.EdgeInsets.all(6),
                  child: pw.Text(
                    h,
                    style: _regularStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ),
              )
              .toList(),
        ),
        if (rows.isEmpty)
          pw.TableRow(
            children: List.generate(
              headers.length,
              (_) => pw.Padding(
                padding: const pw.EdgeInsets.all(6),
                child: pw.Text(
                  'No records',
                  style: _regularStyle(fontSize: 10),
                ),
              ),
            ),
          )
        else
          ...rows.map(
            (row) => pw.TableRow(
              children: row
                  .map(
                    (cell) => pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        cell ?? 'N/A',
                        style: _regularStyle(fontSize: 10),
                      ),
                    ),
                  )
                  .toList(),
            ),
          ),
      ],
    );
  }

  static pw.Widget _buildSummaryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              label,
              style: _regularStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text(value, style: _regularStyle(fontSize: 11)),
        ],
      ),
    );
  }

  Future<Uint8List> generateMemberStatement({
    required MemberModel member,
    required List<ObligationModel> obligations,
    required List<PaymentModel> payments,
    required DateTime reportDate,
  }) async {
    await _ensureFonts();

    final pdf = pw.Document();

    final totalPaid = payments
        .where((p) => p.status == PaymentStatus.approved)
        .fold<double>(0, (sum, p) => sum + p.amount);
    final totalOutstanding = obligations.fold<double>(
      0,
      (sum, o) => sum + o.outstandingBalance,
    );

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(buildBackground: (context) => pw.Container()),
        footer: _buildFooter,
        build: (context) => [
          _buildHeader(
            'Member Statement',
            subtitles: [
              'Report Date: ${_fmtDate(reportDate)}',
              'Member: ${member.fullName}',
              'Email: ${member.email}',
              'Phone: ${member.phoneNumber}',
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Obligations',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: [
              'Title',
              'Type',
              'Amount',
              'Paid',
              'Outstanding',
              'Status',
              'Due Date',
            ],
            rows: obligations.map((o) {
              return [
                o.title,
                o.type.name,
                _fmt(o.amount),
                _fmt(o.paidAmount),
                _fmt(o.outstandingBalance),
                o.status.name,
                _fmtDate(o.dueDate),
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Payments',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: ['Date', 'Amount', 'Method', 'Status'],
            rows: payments.map((p) {
              return [
                _fmtDate(p.createdAt),
                _fmt(p.amount),
                p.method.name,
                p.status.name,
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
              color: PdfColors.grey100,
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Summary',
                  style: _regularStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                _buildSummaryRow('Total Paid:', _fmt(totalPaid)),
                _buildSummaryRow('Total Outstanding:', _fmt(totalOutstanding)),
                _buildSummaryRow(
                  'Net Balance:',
                  _fmt(totalOutstanding - totalPaid),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateLevyReport({
    required LevyModel levy,
    required List<ObligationModel> obligations,
    required List<PaymentModel> payments,
    required int totalMembers,
  }) async {
    await _ensureFonts();

    final pdf = pw.Document();

    final totalTarget = levy.amountPerMember * totalMembers;
    final totalCollected = obligations.fold<double>(
      0,
      (sum, o) => sum + o.paidAmount,
    );
    final totalOutstanding = obligations.fold<double>(
      0,
      (sum, o) => sum + o.outstandingBalance,
    );
    final collectionPercent = totalTarget > 0
        ? (totalCollected / totalTarget * 100).toStringAsFixed(1)
        : '0.0';

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(buildBackground: (context) => pw.Container()),
        footer: _buildFooter,
        build: (context) => [
          _buildHeader(
            'Levy Report',
            subtitles: [
              'Levy: ${levy.title}',
              'Amount per Member: ${_fmt(levy.amountPerMember)}',
              'Member Count: $totalMembers',
              'Total Target: ${_fmt(totalTarget)}',
              'Report Date: ${_fmtDate(DateTime.now())}',
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
              color: PdfColors.grey100,
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Summary',
                  style: _regularStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                _buildSummaryRow('Total Collected:', _fmt(totalCollected)),
                _buildSummaryRow('Total Outstanding:', _fmt(totalOutstanding)),
                _buildSummaryRow('Collection %:', '$collectionPercent%'),
              ],
            ),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Obligations',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: ['Member ID', 'Amount', 'Paid', 'Outstanding', 'Status'],
            rows: obligations.map((o) {
              return [
                o.memberId,
                _fmt(o.amount),
                _fmt(o.paidAmount),
                _fmt(o.outstandingBalance),
                o.status.name,
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Payments',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: ['Date', 'Amount', 'Method', 'Status'],
            rows: payments.map((p) {
              return [
                _fmtDate(p.createdAt),
                _fmt(p.amount),
                p.method.name,
                p.status.name,
              ];
            }).toList(),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateYearlySummary({
    required int year,
    required List<PaymentModel> payments,
    required List<ExpenseModel> expenses,
    required List<ObligationModel> obligations,
  }) async {
    await _ensureFonts();

    final pdf = pw.Document();

    final monthlyIncome = <int, double>{};
    for (var i = 1; i <= 12; i++) {
      monthlyIncome[i] = 0.0;
    }
    for (final p in payments.where((p) => p.status == PaymentStatus.approved)) {
      final m = p.createdAt.month;
      if (p.createdAt.year == year) {
        monthlyIncome[m] = (monthlyIncome[m] ?? 0.0) + p.amount;
      }
    }

    final monthlyExpenses = <int, double>{};
    for (var i = 1; i <= 12; i++) {
      monthlyExpenses[i] = 0.0;
    }
    for (final e in expenses) {
      final m = e.expenseDate.month;
      if (e.expenseDate.year == year) {
        monthlyExpenses[m] = (monthlyExpenses[m] ?? 0.0) + e.amount;
      }
    }

    final totalIncome = monthlyIncome.values.fold<double>(0, (s, v) => s + v);
    final totalExpenses = monthlyExpenses.values.fold<double>(
      0,
      (s, v) => s + v,
    );
    final netBalance = totalIncome - totalExpenses;

    final outstandingTotal = obligations.fold<double>(
      0,
      (sum, o) => sum + o.outstandingBalance,
    );

    final monthNames = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(buildBackground: (context) => pw.Container()),
        footer: _buildFooter,
        build: (context) => [
          _buildHeader(
            'Yearly Financial Summary - $year',
            subtitles: ['Report Date: ${_fmtDate(DateTime.now())}'],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Income (Collections)',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Wrap(
            spacing: 12,
            runSpacing: 8,
            children: List.generate(12, (i) {
              return pw.Container(
                width: 120,
                padding: const pw.EdgeInsets.all(6),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      monthNames[i],
                      style: _regularStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      _fmt(monthlyIncome[i + 1] ?? 0),
                      style: _regularStyle(fontSize: 10),
                    ),
                  ],
                ),
              );
            }),
          ),
          pw.SizedBox(height: 8),
          _buildSummaryRow('Total Income for $year:', _fmt(totalIncome)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Expenses',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Wrap(
            spacing: 12,
            runSpacing: 8,
            children: List.generate(12, (i) {
              return pw.Container(
                width: 120,
                padding: const pw.EdgeInsets.all(6),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      monthNames[i],
                      style: _regularStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      _fmt(monthlyExpenses[i + 1] ?? 0),
                      style: _regularStyle(fontSize: 10),
                    ),
                  ],
                ),
              );
            }),
          ),
          pw.SizedBox(height: 8),
          _buildSummaryRow('Total Expenses for $year:', _fmt(totalExpenses)),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
              color: PdfColors.grey100,
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Net Balance',
                  style: _regularStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                _buildSummaryRow('Net Balance:', _fmt(netBalance)),
                _buildSummaryRow(
                  'Total Outstanding Obligations:',
                  _fmt(outstandingTotal),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateExpenseBreakdown({
    required List<ExpenseModel> expenses,
    required DateTime? startDate,
    required DateTime? endDate,
  }) async {
    await _ensureFonts();

    final pdf = pw.Document();

    final filtered = expenses.where((e) {
      if (startDate != null && e.expenseDate.isBefore(startDate)) return false;
      if (endDate != null) {
        final end = DateTime(
          endDate.year,
          endDate.month,
          endDate.day,
          23,
          59,
          59,
        );
        if (e.expenseDate.isAfter(end)) return false;
      }
      return true;
    }).toList();

    final categoryMap = <ExpenseCategory, List<ExpenseModel>>{};
    for (final e in filtered) {
      categoryMap.putIfAbsent(e.category, () => []).add(e);
    }

    final grandTotal = filtered.fold<double>(0, (sum, e) => sum + e.amount);

    final dateRange = (startDate != null || endDate != null)
        ? '${startDate != null ? _fmtDate(startDate) : 'All time'} - ${endDate != null ? _fmtDate(endDate) : 'All time'}'
        : 'All time';

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(buildBackground: (context) => pw.Container()),
        footer: _buildFooter,
        build: (context) => [
          _buildHeader(
            'Expense Breakdown',
            subtitles: ['Date Range: $dateRange'],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Summary by Category',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: ['Category', 'Count', 'Total Amount'],
            rows: categoryMap.entries.map((entry) {
              final total = entry.value.fold<double>(0, (s, e) => s + e.amount);
              return [
                entry.key.name,
                entry.value.length.toString(),
                _fmt(total),
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Expense Details',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildTable(
            headers: [
              'Date',
              'Category',
              'Amount',
              'Description',
              'Recorded By',
            ],
            rows: filtered.map((e) {
              return [
                _fmtDate(e.expenseDate),
                e.category.name,
                _fmt(e.amount),
                e.description,
                e.createdBy.isEmpty ? 'N/A' : e.createdBy,
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
              color: PdfColors.grey100,
            ),
            child: _buildSummaryRow('Grand Total:', _fmt(grandTotal)),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateFinancialSummary({
    required List<PaymentModel> payments,
    required List<ExpenseModel> expenses,
    required List<MemberModel> members,
    required List<ObligationModel> obligations,
    required DateTime? startDate,
    required DateTime? endDate,
  }) async {
    await _ensureFonts();

    final pdf = pw.Document();

    final approvedPayments = payments.where(
      (p) => p.status == PaymentStatus.approved,
    );
    final filteredPayments = approvedPayments.where((p) {
      if (startDate != null && p.createdAt.isBefore(startDate)) return false;
      if (endDate != null) {
        final end = DateTime(
          endDate.year,
          endDate.month,
          endDate.day,
          23,
          59,
          59,
        );
        if (p.createdAt.isAfter(end)) return false;
      }
      return true;
    });

    final filteredExpenses = expenses.where((e) {
      if (startDate != null && e.expenseDate.isBefore(startDate)) return false;
      if (endDate != null) {
        final end = DateTime(
          endDate.year,
          endDate.month,
          endDate.day,
          23,
          59,
          59,
        );
        if (e.expenseDate.isAfter(end)) return false;
      }
      return true;
    });

    final totalCollections = filteredPayments.fold<double>(
      0,
      (sum, p) => sum + p.amount,
    );
    final onlineTotal = filteredPayments
        .where((p) => p.method == PaymentMethod.online)
        .fold<double>(0, (sum, p) => sum + p.amount);
    final cashTotal = filteredPayments
        .where((p) => p.method == PaymentMethod.cash)
        .fold<double>(0, (sum, p) => sum + p.amount);
    final bankTotal = filteredPayments
        .where((p) => p.method == PaymentMethod.bankTransfer)
        .fold<double>(0, (sum, p) => sum + p.amount);

    final totalExpenses = filteredExpenses.fold<double>(
      0,
      (sum, e) => sum + e.amount,
    );

    final expensesByCategory = <ExpenseCategory, double>{};
    for (final e in filteredExpenses) {
      expensesByCategory[e.category] =
          (expensesByCategory[e.category] ?? 0.0) + e.amount;
    }

    final totalOutstanding = obligations.fold<double>(
      0,
      (sum, o) => sum + o.outstandingBalance,
    );

    final totalMembers = members.length;
    final activeMembers = members.where((m) => m.isActive).length;

    final dateRangeText = (startDate != null || endDate != null)
        ? '${startDate != null ? _fmtDate(startDate) : 'All time'} - ${endDate != null ? _fmtDate(endDate) : 'All time'}'
        : null;

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(buildBackground: (context) => pw.Container()),
        footer: _buildFooter,
        build: (context) => [
          _buildHeader(
            'Financial Summary',
            subtitles: [
              if (dateRangeText != null) 'Period: $dateRangeText',
              'Report Date: ${_fmtDate(DateTime.now())}',
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Membership',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildSummaryRow('Total Members:', totalMembers.toString()),
          _buildSummaryRow('Active Members:', activeMembers.toString()),
          pw.SizedBox(height: 16),
          pw.Text(
            'Collections',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildSummaryRow('Total Approved Payments:', _fmt(totalCollections)),
          _buildSummaryRow('Online:', _fmt(onlineTotal)),
          _buildSummaryRow('Cash:', _fmt(cashTotal)),
          _buildSummaryRow('Bank Transfer:', _fmt(bankTotal)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Expenses',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildSummaryRow('Total Expenses:', _fmt(totalExpenses)),
          ...expensesByCategory.entries.map(
            (e) => _buildSummaryRow('${e.key.name}:', _fmt(e.value)),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Net Position',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildSummaryRow(
            'Collections minus Expenses:',
            _fmt(totalCollections - totalExpenses),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Outstanding Obligations',
            style: _regularStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _buildSummaryRow('Total Outstanding:', _fmt(totalOutstanding)),
        ],
      ),
    );

    return pdf.save();
  }
}
