import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../core/constants/enums.dart';
import '../models/receipt_model.dart';

/// Pure Dart service for generating receipt PDFs.
class ReceiptService {
  static final _currencyFormat = NumberFormat.currency(
    symbol: '₦',
    decimalDigits: 0,
  );
  static final _dateTimeFormat = DateFormat('dd MMM yyyy, hh:mm a');

  static String _fmt(double amount) => _currencyFormat.format(amount);
  static String _fmtDateTime(DateTime date) => _dateTimeFormat.format(date);

  String _methodLabel(PaymentMethod method) {
    switch (method) {
      case PaymentMethod.online:
        return 'Online';
      case PaymentMethod.cash:
        return 'Cash';
      case PaymentMethod.bankTransfer:
        return 'Bank Transfer';
    }
  }

  String _statusLabel(PaymentStatus status) {
    switch (status) {
      case PaymentStatus.approved:
        return 'Approved';
      case PaymentStatus.pending:
        return 'Pending';
      case PaymentStatus.rejected:
        return 'Rejected';
    }
  }

  Future<Uint8List> generateReceiptPdf({
    required ReceiptModel receipt,
    required String associationName,
    String? associationAddress,
    String? associationPhone,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          buildBackground: (context) => pw.FullPage(
            ignoreMargins: true,
            child: pw.Container(
              margin: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.green800, width: 2.5),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
            ),
          ),
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 8, right: 16, bottom: 8),
          child: pw.Text(
            'Generated by Age Grade Finance App  |  Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
        ),
        build: (context) => [
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildAssociationHeader(
              associationName,
              associationAddress,
              associationPhone,
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildReceiptTitle(),
          ),
          pw.SizedBox(height: 12),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildReceiptNumber(receipt.receiptNumber),
          ),
          pw.SizedBox(height: 20),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildDetailsSection(receipt),
          ),
          pw.SizedBox(height: 20),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildObligationsTable(receipt.allocatedObligations),
          ),
          pw.SizedBox(height: 24),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildTotalSection(receipt.amount),
          ),
          pw.SizedBox(height: 32),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(horizontal: 24),
            child: _buildThankYouMessage(),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildAssociationHeader(
    String name,
    String? address,
    String? phone,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.SizedBox(height: 8),
        pw.Text(
          name,
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.green900,
          ),
          textAlign: pw.TextAlign.center,
        ),
        if (address != null && address.isNotEmpty) ...[
          pw.SizedBox(height: 2),
          pw.Text(
            address,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            textAlign: pw.TextAlign.center,
          ),
        ],
        if (phone != null && phone.isNotEmpty) ...[
          pw.SizedBox(height: 2),
          pw.Text(
            'Tel: $phone',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            textAlign: pw.TextAlign.center,
          ),
        ],
        pw.SizedBox(height: 8),
        pw.Divider(color: PdfColors.green800, thickness: 2),
      ],
    );
  }

  pw.Widget _buildReceiptTitle() {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      decoration: pw.BoxDecoration(
        color: PdfColors.green50,
        border: pw.Border.all(color: PdfColors.green800, width: 1.5),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Center(
        child: pw.Text(
          'OFFICIAL RECEIPT',
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.green900,
            letterSpacing: 3,
          ),
        ),
      ),
    );
  }

  pw.Widget _buildReceiptNumber(String receiptNumber) {
    return pw.Center(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text(
            'Receipt No.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            receiptNumber,
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.black,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildDetailsSection(ReceiptModel receipt) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        color: PdfColors.grey50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _buildDetailRow('Member Name:', receipt.memberName),
          pw.SizedBox(height: 6),
          _buildDetailRow('Payment Date:', _fmtDateTime(receipt.paymentDate)),
          pw.SizedBox(height: 6),
          _buildDetailRow('Payment Method:', _methodLabel(receipt.method)),
          pw.SizedBox(height: 6),
          _buildDetailRow(
            'Payment Status:',
            _statusLabel(PaymentStatus.approved),
          ),
          pw.SizedBox(height: 12),
          pw.Divider(color: PdfColors.grey300, thickness: 0.5),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Text(
                  'Amount Paid',
                  style: pw.TextStyle(
                    fontSize: 13,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.Text(
                _fmt(receipt.amount),
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.green800,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildDetailRow(String label, String value) {
    return pw.Row(
      children: [
        pw.Expanded(
          flex: 2,
          child: pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
        ),
        pw.Expanded(
          flex: 3,
          child: pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.black,
            ),
          ),
        ),
      ],
    );
  }

  pw.Widget _buildObligationsTable(List<Map<String, dynamic>> obligations) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Allocated Obligations',
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(2),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _tableCell('Obligation Title', isHeader: true),
                _tableCell('Amount Allocated', isHeader: true),
              ],
            ),
            if (obligations.isEmpty)
              pw.TableRow(
                children: [
                  _tableCell('No obligations allocated', isHeader: false),
                  _tableCell('-', isHeader: false),
                ],
              )
            else
              ...obligations.map((o) {
                final title = o['title']?.toString() ?? 'Unknown';
                final amount = (o['amount'] as num?)?.toDouble() ?? 0.0;
                return pw.TableRow(
                  children: [
                    _tableCell(title, isHeader: false),
                    _tableCell(_fmt(amount), isHeader: false),
                  ],
                );
              }),
          ],
        ),
      ],
    );
  }

  pw.Widget _tableCell(String text, {required bool isHeader}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  pw.Widget _buildTotalSection(double amount) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.green800, width: 1.5),
        color: PdfColors.green50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              'Total Amount',
              style: pw.TextStyle(
                fontSize: 13,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.green900,
              ),
            ),
          ),
          pw.Text(
            _fmt(amount),
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.green800,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildThankYouMessage() {
    return pw.Center(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text(
            'Thank you for your payment!',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey700,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'This receipt was automatically generated by the Age Grade Finance App.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
        ],
      ),
    );
  }
}
